<a href="https://colab.research.google.com/github/zfanli/colab-notebooks/blob/master/training_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## training tensorflow

Specify the version of tensorflow for further use.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


Then import tensorflow.

In [3]:
import tensorflow as tf
print(tf.__version__)

2.1.0


Play with tensorflow.

The shape of a tensor looks like the dimensions of the data.

Shape `[3, 2]` means the data have 3 rows and 2 columns.

Shepe `[3, 4, 5]` means the data have 3 blocks with each block has 4 rows and 5 columns.

And so on.

In [0]:
play = tf.zeros([3,4,5,2], dtype=tf.int32)
print(play)

We get a varibale named `play` above.

It has a shape of `[3, 4, 5, 2]`, which means it contains 3 x 4 x 5 x 2 zeros.

Let me calculate it!

In [16]:
print(3 * 4 * 5 * 2)

120


It's 120!

We got 120 zeros inside `play`!

Let's reshape it into one array only, which means there will be only one dimension in the target data.

Let's do it.

In [18]:
tf.reshape(play, [120])

<tf.Tensor: shape=(120,), dtype=int32, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>

Cool! Reshape is convenient!

Just do some play with reshape and see the result.

Use `-1` to indicate that we do not care this argument, and then it will be calculate automatically by the tensorflow itself.

But if the number of values is impossible to be divided by the given arguments, an invalid argument error will be thrown.

It is resonable.

In [23]:
tf.reshape(play, [10, -1])

<tf.Tensor: shape=(10, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>